site_name: Tomography Analysis Tool Documentation

docs_dir: docs

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

nav:
  - Home: "index.md"
  - "User Guide":
    - "Installation": "user-guide/installation.md"
    - "Interface manual": "user-guide/manual.md"
  - About:
    - "License": "license.md"
    - "Contributing": "contributing.md"
